version: '3.9'

services:
  web:
    build: ./backend
    container_name: web_container
    command: 
      - /bin/sh
      - -c
      - |
        . /usr/src/app/entrypoint.sh 
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.example
    depends_on:
      - db
      
  tailwind:
    build: ./node_files
    container_name: tailwind_container
    command: npm run tailwind
    tty: true
    volumes:
      - ./node_files:/home/node/app
      - ./backend:/backend
    depends_on:
      - web

  webpack:
    build: ./node_files
    container_name: webpack_container
    command: npm run webpack
    volumes:
      - ./node_files:/home/node/app
      - ./backend:/backend
    depends_on:
      - web  
  db:
    image: postgres:16-bullseye

    container_name: postgresql_container
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
volumes:
  postgres_data_dev:
