version: '3.9'

services:
  web:
    build: ./backend
    command: 
      - /bin/sh
      - -c
      - |
        . /usr/src/app/entrypoint.sh 
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.example
    depends_on:
      - db
      
  tailwind:
    build: ./node_files
    command: npm run tailwind
    tty: true
    volumes:
      - volume-preserve-tiptap-node-modules-tailwind:/app/node_modules
      - ./node_files:/app
      - ./backend:/backend
    depends_on:
      - web

  webpack:
    build: ./node_files
    command: npm run webpack
    volumes:
      - volume-preserve-tiptap-node-modules-webpack:/app/node_modules
      - ./node_files:/app
      - ./backend:/backend
    depends_on:
      - web  
    ports:
      - 9000:9000
  db:
    image: postgres:16-bullseye
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - 5431:5432
volumes:
  postgres_data_dev:
  volume-preserve-tiptap-node-modules-tailwind:
  volume-preserve-tiptap-node-modules-webpack:
