# Generated by Django 5.0.6 on 2024-07-05 15:06

import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_default', models.TextField()),
                ('body_editorjs', django_editorjs_fields.fields.EditorJsJSONField()),
                ('body_editorjs_text', django_editorjs_fields.fields.EditorJsTextField()),
            ],
        ),
    ]
