# Generated by Django 5.0.6 on 2024-07-06 23:10

import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_imagepost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="body_default",
        ),
        migrations.RemoveField(
            model_name="post",
            name="body_editorjs",
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="name", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="body_editorjs_text",
            field=django_editorjs_fields.fields.EditorJsTextField(
                blank=True, null=True
            ),
        ),
    ]
