# Generated by Django 5.0.6 on 2024-08-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_curso_imagecurso"),
    ]

    operations = [
        migrations.RenameField(
            model_name="curso",
            old_name="title",
            new_name="name",
        ),
    ]
