# Generated by Django 5.0.6 on 2024-08-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_title_curso_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="description",
        ),
        migrations.AddField(
            model_name="curso",
            name="body",
            field=models.TextField(blank=True),
        ),
    ]
