# Generated by Django 5.0.6 on 2024-08-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_curso_description_curso_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="body",
            field=models.TextField(),
        ),
    ]
